name: Provision App Service (Terraform)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "infra/**.tf"
      - "infra/**.tfvars"

permissions:
  id-token: write   # for OIDC
  contents: read

env:
  ARM_USE_OIDC: true
  ARM_TENANT_ID:       ${{ secrets.AZURE_TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID:       ${{ secrets.AZURE_CLIENT_ID }}

jobs:
  tf-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

        # Optional: show which principal is authenticated
      - name: WhoAmI
        run: |
          echo "ClientId: $ARM_CLIENT_ID"
          echo "Sub: $ARM_SUBSCRIPTION_ID"

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars

      - name: Terraform Apply (main only)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -var-file=dev.tfvars
